# AMD Developer Cloud Validation Workflow
## Bonsai 2 Ternary Vulkan Performance on MI300X
## Purpose: Benchmark Bonsai 2 on MI300X, extract configuration for RX 6600

## Prerequisites (after claiming $100 credits)
1. AMD Developer Cloud account activated
2. SSH key paired with account
3. `amdctl` or `devcloud` CLI installed
4. Access to MI300X instance (gfx90a or gfx1030)

## Step 1: Reserve MI300X Instance
```powershell
# Login to AMD Developer Cloud
amdctl login  # or: devcloud login

# Reserve MI300X for 80 hours (approx $85)
amdctl reserve \
  --instance-type mi300x \
  --duration 80h \
  --region us-east-1 \
  --project bonsai2-optimization

# Note instance credentials
# - SSH: ssh amdcloud@instance-XX.amer.datadoghq.com
# - Password: generated by system
```

## Step 2: Build Prism llama.cpp with ROCm on MI300X
```powershell
# Connect via SSH
ssh amdcloud@instance-XX.amer.datadoghq.com

# Update and install deps
sudo apt update && sudo apt install -y build-essential cmake git

# Clone prism llama.cpp fork
git clone https://github.com/prism-ml/llama.cpp.git
cd llama.cpp

# Build with ROCm backend (for MI300X)
# Note: gfx90a is MI300X architecture
cmake -B build \
  -DGGML_HIP=ON \
  -DAMDGPU_TARGETS=gfx90a \
  -DGGML_VULKAN=OFF \  # ROCm backend, not Vulkan
  -DGGML_OPENMP=ON \
  -DCMAKE_BUILD_TYPE=Release

# Build
cmake --build build --config Release -j 64

# Copy binary to working dir
cp build/bin/Release/llama-server.exe .
```

## Step 3: Download and Prepare Bonsai 2 Model
```powershell
# Download model (5.54 GB)
git lfs install
git clone https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf.git

# Or direct download if HF is slow
wget "https://huggingface.co/api/models/prism-ml/Ternary-Bonsai-2-27B-gguf/git/lfs/Ternary-Bonsai-2-27B-PTQ1_0.gguf?private_token=YOUR_TOKEN"

# Verify file
ls -lh Ternary-Bonsai-2-27B-PTQ1_0.gguf  # should be ~5.5 GB
```

## Step 4: Benchmark Suite
### 4.1: Baseline - CPU Only (no GPU offload)
```powershell
./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device cpu \
  -ngl 0 -c 8192 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9103
```

### 4.2: ROCm GPU Offload (full)
```powershell
# Set HIP device (MI300X is device 0 by default)
export HIP_VISIBLE_DEVICES=0

./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device HIP \
  -ngl 99 -c 8192 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9104
```

### 4.3: Quantization Benchmark Matrix
For each quantization level Q_LEVEL in [Q2_0, Q3_0, Q4_0, Q5_0, Q8_0]:
```powershell
# Q2_0 (ROCMFPX - low bit, fastest but lowest quality)
./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device HIP \
  -ngl 99 -c 8192 \
  -q Q2_0 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9110 \
  --log-logits

# Q3_0 (ROCMFPX)
./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device HIP \
  -ngl 99 -c 8192 \
  -q Q3_0 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9111 \
  --log-logits

# Q4_0
./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device HIP \
  -ngl 99 -c 8192 \
  -q Q4_0 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9112 \
  --log-logits

# Q5_0
./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device HIP \
  -ngl 99 -c 8192 \
  -q Q5_0 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9113 \
  --log-logits

# Q8_0
./llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf \
  --device HIP \
  -ngl 99 -c 8192 \
  -q Q8_0 \
  -ctk q8_0 -ctv q8_0 \
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 \
  --port 9114 \
  --log-logits
```

### 4.4: Throughput Measurement
For each benchmark run, measure:
- **tok/s** (tokens per second) - primary metric
- **time-to-first-token** (TTFT)
- **memory usage** (VRAM)
- **quality probes** (tool-call success rate)

Use `jq` to parse logs or capture output to `.log` files:
```powershell
./llama-server.exe ... > benchmark_Q4_0.log 2>&1
# Then parse:
grep "tok/s" benchmark_Q4_0.log
```

## Step 5: Data Collection & Documentation
### 5.1: Create results directory
```powershell
mkdir -p /home/amdcloud/results
```

### 5.2: Save each benchmark result
```powershell
# Example result format (save to JSON)
{
  "quantization": "Q4_0",
  "device": "HIP-MI300X",
  "tok_s": 45.2,
  "context": 8192,
  "vrAM_GB": 14.2,
  "ttft_ms": 1200,
  "quality_pass": true
} | Out-File results/Q4_0.json
```

### 5.3: Summary table (manual creation after all runs)
| Quant | tok/s | VRAM (GB) | Quality | Notes |
|-------|-------|-----------|---------|-------|
| Q2_0  | ?     | ?         | low     |       |
| Q3_0  | ?     | ?         | medium  |       |
| Q4_0  | ?     | ?         | good    |       |
| Q5_0  | ?     | ?         | great   |       |
| Q8_0  | ?     | ?         | best    | slowest |

## Step 6: Extract RX 6600 Porting Guide
### 6.1: Map MI300X results to RX 6600 constraints
```powershell
# RX 6600 has 8 GB VRAM, RDNA2 architecture
# MI300X has 192 GB HBM3

# Key insights to document:
1. Which quantizations fit in 8 GB VRAM on RX 6600?
   - Q4_K_M: ~8 GB (fits)
   - Q5_K_M: ~11 GB (does NOT fit, needs system RAM)
   - Q8_0: ~22 GB (does NOT fit)

2. What speedup is possible vs 3.3 tok/s baseline?
   - If MI300X Q4_0: 45 tok/s → expect 1-2 tok/s on RX 6600 (13-45x slower, but still >3.3)
   - If MI300X Q3_0: 60 tok/s → expect 2-3 tok/s on RX 6600 (2-3x improvement)

3. Is ternary Vulkan kernel feasible?
   - If MI300X shows good HIP ternary performance → port to Vulkan
   - If MI300X falls back to CPU → Vulkan kernel essential

### 6.2: Create optimized RX 6600 command
Based on benchmark results, create updated BONSAI2.cmd:

```powershell
:: OPTIMIZED for RX 6600 (based on MI300X findings)
:: If Q4_K_M fits and gives best speed/quality:
llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf ^
  --device Vulkan1 ^
  -ngl 99 -c 8192 ^
  -q Q4_K_M ^
  -ctk q8_0 -ctv q8_0 ^
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 ^
  -port 9103

:: If only Q3_0 fits (lower quality but faster):
llama-server.exe -m Ternary-Bonsai-2-27B-PTQ1_0.gguf ^
  --device Vulkan1 ^
  -ngl 99 -c 8192 ^
  -q Q3_0_ROCMFPX ^
  -ctk q8_0 -ctv q8_0 ^
  -fa on --temp 0.5 --top-p 0.85 --top-k 20 ^
  -port 9103
```

## Step 7: Cleanup & Credit Tracking
```powershell
# Release instance (stop clock on credits)
amdctl release --instance-type mi300x

# Total credits used: document
echo "MI300X benchmark complete. Credits used: ~$85 of $100"
echo "Remaining: $10 for contingency/hybrid offload script"
```

## Expected Outcomes
| Outcome | If True | Action |
|---------|---------|--------|
| **Q4_K_M achieves 20+ tok/s on MI300X** | Ternary works on RDNA3-class | Port Q4 kernel to RX 6600 Vulkan |
| **Q3_0_ROCMFPX achieves 30+ tok/s on MI300X** | Low-bit works well | Use Q3_0 on RX 6600 (better than current 3.3) |
| **All quants < 10 tok/s on MI300X** | Instinct also limited | Focus on hybrid offload (Option 2) or quant optimization (Option 3) |
| **MI300X full ROCm fails, only CPU works** | Backend issue | Abandon GPU path, focus on CPU+GPU hybrid |

---
*Workflow version 1.0 - For AMD AI Developer Program credit usage*